### ISSUE TITLE
'copy customisation files' task fails

### ISSUE THREAD

**Issue by tjanez** [ginsys/ansible-role-seafile#5]
Hi!

Here is the output of running Ansible:
```
[tadej@tlinux64 ansible-janez-deploy]$ pwd
/home/tadej/Apps/Ansible/ansible-janez-deploy
[tadej@tlinux64 ansible-janez-deploy]$ ansible-playbook -v -i stage site.yml --ask-vault-pass --start-at-task="seafile | copy customisation files"
Vault password: 

PLAY [Janež storage servers] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [abraham.ja.nez.local]

TASK: [seafile | copy customisation files] ************************************ 
fatal: [abraham.ja.nez.local] => input file not found at /home/tadej/Apps/Ansible/ansible-janez-deploy/roles/seafile/files/files/seafile/custom or /home/tadej/Apps/Ansible/ansible-janez-deploy/files/seafile/custom

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/tadej/site.retry

abraham.ja.nez.local       : ok=1    changed=0    unreachable=1    failed=0   

[tadej@tlinux64 ansible-janez-deploy]$
```
The `src` location of this task is `files/seafile/custom`, however, I don't see that in the git repo?

**Comment by srvg** [comment]
Hi @tjanez 

I tseems te failing task is  not part of the role, but comes from the example playbook I provide, `example/seafile.yml`.

Obviously that example playbook is something you need to adapt to your local deploy. `files/seafile/custom/` contains seafile customisations, as per http://manual.seafile.com/config/seahub_customization.html 
```
$ tree -if files/seafile/custom/
files/seafile/custom
files/seafile/custom/ginsys_seafile.css
files/seafile/custom/ginsys_seafile_logo.png
files/seafile/custom/templates
files/seafile/custom/templates/footer.html
```
These files are obviously personal, so not meant to be blindly copied.

**Comment by tjanez** [comment]
Hi @srvg,

thanks for such a quick reply!

No, the failing task is not from `example/seafile.yml`, but comes from the role. It is at the end of file `tasks/configure.yml`, which gets included by `tasks/main.yml`.

Thanks for explaining what the files under `files/seafile/custom` are.
I think they should not be required for running the role, are they?

**Comment by srvg** [comment]
You are right, seems that was a change I made in the latest commit, 8c1d97e. I'm not sure why right now. Perhaps you could stick with https://github.com/ginsys/ansible-role-seafile/releases/tag/4.0 for now.

That latest update was probably made from my production checkout, and I must have made a mistake that made this unuseable from a fresh install point of view. I'll see to retest that on a test server, and sort it out. Can't make any direct promises on a time frame though.

Thanks for your report.

**Comment by srvg** [comment]
@tjanez I pushed some updates to the master branch, that might fix your issue. Woyld you be able to give this a a test run? This should also confirm support for the recently released seafile upstream 4.1.x branch.

**Comment by lexrus** [comment]
@srvg `ignore_errors` normally applies to the target host. I still get the error with the latest code.

**Comment by srvg** [comment]
I upgrade the role to support 4.2.2, and rewrote the logic to handle custom file paths.

@tjanez @lexrus can you confirm this works out for you?

**Comment by lexrus** [comment]
@srvg I set seafile_install_version: '4.2.2' and it failed:

```
TASK: [Ginsys.seafile | check supported versions] ***************************** 
failed: [128.199.231.231] => {"assertion": "\".\".join(seafile_install_version.split(\".\")[0:2]) in SEAFILE_SUPPORTED_VERSIONS", "evaluated_to": false, "failed": true}

FATAL: all hosts have already failed -- aborting
```

**Comment by lexrus** [comment]
Well I guess there is no 4.2.2 in their official repo. Should be `seafile_install_version: '4.2.1'`

Also, I've changed `vars/main.yml` to add 4.2.
``` yaml
SEAFILE_SUPPORTED_VERSIONS:
  - '3.0'
  - '3.1'
  - '4.0'
  - '4.2'
```

At last, everything goes well.
Thank you.

**Comment by srvg** [comment]
@lexrus that sounds like you don't have the latest version of the role, see
https://github.com/ginsys/ansible-role-seafile/blob/devel/vars/main.yml#L10
which does contain 4.2 (and not 3.x any more)

Did you use the currently latest devel version (which matches the 4.2.2 tag)?

Also upstream does have a 4.2.2, see 
https://bintray.com/artifact/download/seafile-org/seafile/seafile-server_4.2.2_x86-64.tar.gz

however, the download url changed recently (formerly bitbucket), if you use an older version of the role, that could explain why it barfs on 4.2.2 and not 4.2.1.

NB: the  import of this updated version in galaxy is stuck...

**Comment by lexrus** [comment]
Oh, my mistake. I'll try the latest code ASAP.

**Comment by lexrus** [comment]
Failed on a brand new Debian 8 hosted on DigitalOcean.

```
TASK: [Ginsys.seafile | copy default avatars to custom data dir] ************** 
failed: [128.199.231.231] => {"changed": false, "cmd": "ORI='/home/seafile/seafile/seafile-server-latest/seahub/media/avatars';\n rsync -ai ${ORI}.ori/ $ORI/", "delta": "0:00:00.109638", "end": "2015-06-01 03:57:46.286503", "rc": 11, "start": "2015-06-01 03:57:46.176865", "stdout_lines": [], "warnings": []}
stderr: rsync: mkdir "/home/seafile/seafile/seafile-server-latest/seahub/media/avatars" failed: File exists (17)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]

FATAL: all hosts have already failed -- aborting
```

2nd run:
```
TASK: [Ginsys.seafile | move the default avatars directory out of the way] **** 
failed: [128.199.231.231] => {"changed": false, "cmd": "ORI='/home/seafile/seafile/seafile-server-latest/seahub/media/avatars'; test -e $ORI && (test -L $ORI || mv -v $ORI ${ORI}.ori)", "delta": "0:00:00.005949", "end": "2015-06-01 03:59:05.266706", "rc": 1, "start": "2015-06-01 03:59:05.260757", "stdout_lines": [], "warnings": []}

FATAL: all hosts have already failed -- aborting
```

**Comment by srvg** [comment]
ok, funky, need to test that myself to understand the error, as this didn't occur in my testing

**Comment by lexrus** [comment]
Same error on an Ubuntu 14.04 box.

**Comment by srvg** [comment]
This time fully testing it on a clean machine and ironing out a couple of bugs. Apologies for not having done that earlier.

**Comment by srvg** [comment]
@lexrus I pushed an update on the devel branch that should fix everything. Tested it with and without providing a customisation directory (https://github.com/ginsys/ansible-role-seafile/blob/devel/defaults/main.yml#L30) on a clean Ubuntu 14.04 vm.

**Comment by lexrus** [comment]
@srvg It works smoothly on Debian 8. But failed on Ubuntu 15.
```
TASK: [Ginsys.seafile | enable init services] ********************************* 
failed: [128.199.180.116] => (item={'os_family': ['Debian', 'RedHat'], 'name': 'seafile'}) => {"failed": true, "item": {"name": "seafile", "os_family": ["Debian", "RedHat"]}}
msg: Error when trying to enable seafile: rc=1 Synchronizing state for seafile.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d seafile defaults
Executing /usr/sbin/update-rc.d seafile enable
Failed to execute operation: No such file or directory

skipping: [128.199.180.116] => (item={'os_family': ['RedHat'], 'name': 'seahub'})

FATAL: all hosts have already failed -- aborting
```

**Comment by lexrus** [comment]
Ubuntu 15 replaced upstart with systemd. I don't know if they are compatible with each other.

**Comment by srvg** [comment]
Thanks for your feedback, @lexrus. I tested myself on Ubuntu 14.04, which is an LTS release. I'm not up to speed with 15.04 nor systemd, and do not plan to explicitly support that (patches would be accepted though) as imho, LTS releases are what one should use for such production grade applications. I updated  the galaxy meta info accordingly, and "released" 4.2.1 as latest version of this role.
